---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory for web
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"
    remote_src: no
    mode: preserve

    
- name: Executing node and run
  shell:
    cmd: pm2 start ~/web/index.js --force

- name: "Export env"
  become: true
  shell:  |
    touch /etc/profile.d/env.sh
    echo export TYPEORM_HOST=$TYPTYPEORM_HOST >> /etc/profile.d/env.sh
    echo export TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> /etc/profile.d/env.sh
    echo export TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> /etc/profile.d/env.sh
    echo export TYPEORM_HOST=$TYPEORM_HOST >> /etc/profile.d/env.sh
    echo export TYPEORM_PORT=$TYPEORM_PORT >> /etc/profile.d/env.sh
    echo export TYPEORM_USERNAME=$TYPEORM_USERNAME >> /etc/profile.d/env.sh
    echo export TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> /etc/profile.d/env.sh
    echo export TYPEORM_DATABASE=$TYPEORM_DATABASE >> /etc/profile.d/env.sh
    echo export TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> /etc/profile.d/env.sh
    echo export TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> /etc/profile.d/env.sh
    . /etc/environment
    . ~/.bashrc